// <auto-generated />
using System;
using GymManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement.Infrastructure.Migrations
{
    [DbContext(typeof(GymContext))]
    partial class GymContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagement.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("UserId")
                        .HasName("PK__Admins__B9BE370F5EAC4B29");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Client", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("PK__Clients__B9BE370F76341260");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3213E83F3E1F5BB7");

                    b.HasIndex("TypeId");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3213E83F3FBFB0EA");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MembershipStatuses");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3213E83F685A2642");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MembershipTypes");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.ScheduledSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Schedule__3213E83F39228270");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_sessions_client");

                    b.HasIndex("StatusId");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("idx_sessions_trainer");

                    b.HasIndex("TrainingTypeId");

                    b.HasIndex("SessionDate", "StartTime")
                        .HasDatabaseName("idx_sessions_date_time");

                    b.ToTable("ScheduledSessions");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.SessionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SessionS__3213E83F09D3A44E");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SessionStatuses");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Speciali__3213E83FDAB2530F");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Trainer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Trainers__B9BE370FEA91E35D");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.TrainingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Training__3213E83F6E580E8E");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainingCategories");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultDuration")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Training__3213E83F8711FA15");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainingTypes");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83F0AEA0218");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.UserMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserMemb__3213E83FFEE12C1D");

                    b.HasIndex("ClientId");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("StatusId");

                    b.ToTable("UserMemberships");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Admin", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("GymManagement.Domain.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admins_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Client", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("GymManagement.Domain.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipPlan", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.MembershipType", "Type")
                        .WithMany("MembershipPlans")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_membership_plans_type");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.ScheduledSession", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.Client", "Client")
                        .WithMany("ScheduledSessions")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_sessions_client");

                    b.HasOne("GymManagement.Domain.Entities.SessionStatus", "Status")
                        .WithMany("ScheduledSessions")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("fk_sessions_status");

                    b.HasOne("GymManagement.Domain.Entities.Trainer", "Trainer")
                        .WithMany("ScheduledSessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sessions_trainer");

                    b.HasOne("GymManagement.Domain.Entities.TrainingType", "TrainingType")
                        .WithMany("ScheduledSessions")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_sessions_training_type");

                    b.Navigation("Client");

                    b.Navigation("Status");

                    b.Navigation("Trainer");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Trainer", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Trainers")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trainers_specialization");

                    b.HasOne("GymManagement.Domain.Entities.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("GymManagement.Domain.Entities.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainers_user");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.TrainingType", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.TrainingCategory", "Category")
                        .WithMany("TrainingTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_training_types_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.UserMembership", b =>
                {
                    b.HasOne("GymManagement.Domain.Entities.Client", "Client")
                        .WithMany("UserMemberships")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_user_memberships_client");

                    b.HasOne("GymManagement.Domain.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany("UserMemberships")
                        .HasForeignKey("MembershipPlanId")
                        .IsRequired()
                        .HasConstraintName("fk_user_memberships_plan");

                    b.HasOne("GymManagement.Domain.Entities.MembershipStatus", "Status")
                        .WithMany("UserMemberships")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("fk_user_memberships_status");

                    b.Navigation("Client");

                    b.Navigation("MembershipPlan");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Client", b =>
                {
                    b.Navigation("ScheduledSessions");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipPlan", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipStatus", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.MembershipType", b =>
                {
                    b.Navigation("MembershipPlans");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.SessionStatus", b =>
                {
                    b.Navigation("ScheduledSessions");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("ScheduledSessions");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.TrainingCategory", b =>
                {
                    b.Navigation("TrainingTypes");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.TrainingType", b =>
                {
                    b.Navigation("ScheduledSessions");
                });

            modelBuilder.Entity("GymManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
